### ISSUE TITLE
Hi addy

### ISSUE THREAD

**Issue by tjw0lf** [addy-dclxvi/Parla-Conky#1]
This is TJ Wolf. can you do me a favor and fix the spotter conky for spotify. Erik's been MIA not answering for some reason. Its not showing covers for some reason. I get wget = url missing. Here is the link to it
https://github.com/erikdubois/Aureola

**Comment by addy-dclxvi** [comment]
Upss..
You shouldn't ask it to my issue pages. You can contact me via Gmail or Hangout instead.
But I will try to help. Spotter conky is based on conky-spotify by Madh93. I see conky-spotify just updated 21 days ago, and Spotter conky last update is in the late of 2016. So, You can try to use conky-spotify cover.sh & imgurl.sh . You can get it here https://github.com/Madh93/conky-spotify/tree/master/scripts .
Sorry I can't give You further support, I don't have Spotify and any Spotify conkies.

**Comment by tjw0lf** [comment]
whats your hangouts name

**Comment by tjw0lf** [comment]
Hi addy i need your help with i3. config. i did it right but it doesn't look right i need an expert
